var modules =
[
    [ "ACMP driver APIs", "group__acmp__interface.html", "group__acmp__interface" ],
    [ "ADC12 driver APIs", "group__adc12__interface.html", "group__adc12__interface" ],
    [ "ADC16 driver APIs", "group__adc16__interface.html", "group__adc16__interface" ],
    [ "BACC driver APIs", "group__bacc__interface.html", "group__bacc__interface" ],
    [ "BKEY driver APIs", "group__bkey__interface.html", "group__bkey__interface" ],
    [ "BPOR driver APIs", "group__bpor__interface.html", "group__bpor__interface" ],
    [ "BUTN driver APIs", "group__butn__interface.html", "group__butn__interface" ],
    [ "CAM driver APIs", "group__cam__interface.html", "group__cam__interface" ],
    [ "CAN driver APIs", "group__can__interface.html", "group__can__interface" ],
    [ "CLOCK driver APIs", "group__clock__interface.html", "group__clock__interface" ],
    [ "COMMON driver APIs", "group__common__interface.html", "group__common__interface" ],
    [ "DAO driver APIs", "group__dao__interface.html", "group__dao__interface" ],
    [ "DMA driver APIs", "group__dma__interface.html", "group__dma__interface" ],
    [ "DMAMUX driver APIs", "group__dmamux__interface.html", "group__dmamux__interface" ],
    [ "DRAM driver APIs", "group__dram__interface.html", "group__dram__interface" ],
    [ "Display_common driver APIs", "group__Display__common__interface.html", "group__Display__common__interface" ],
    [ "Enet driver APIs", "group__enet__interface.html", "group__enet__interface" ],
    [ "FFA driver APIs", "group__ffa__interface.html", "group__ffa__interface" ],
    [ "GPIO driver APIs", "group__gpio__interface.html", "group__gpio__interface" ],
    [ "GPIOM driver APIs", "group__gpiom__interface.html", "group__gpiom__interface" ],
    [ "GPTMR driver APIs", "group__gptmr__interface.html", "group__gptmr__interface" ],
    [ "HALL driver APIs", "group__hall__interface.html", "group__hall__interface" ],
    [ "HPMicro Math Functions", "group__hpmmath.html", "group__hpmmath" ],
    [ "HPMicro Motor Control Library", "group__middleware__mcl__interfaces.html", "group__middleware__mcl__interfaces" ],
    [ "I2C driver APIs", "group__i2c__interface.html", "group__i2c__interface" ],
    [ "I2S common driver APIs", "group__i2s__common__interface.html", "group__i2s__common__interface" ],
    [ "I2S driver APIs", "group__i2s__interface.html", "group__i2s__interface" ],
    [ "INTERRUPT driver APIs", "group__irq__interface.html", "group__irq__interface" ],
    [ "JPEG driver APIs", "group__Jpeg__interface.html", "group__Jpeg__interface" ],
    [ "L1CACHE driver APIs", "group__l1cache__interface.html", "group__l1cache__interface" ],
    [ "LCD driver APIs", "group__lcd__interface.html", "group__lcd__interface" ],
    [ "MBX driver APIs", "group__mbx__interface.html", "group__mbx__interface" ],
    [ "MCHTMR driver APIs", "group__mchtmr__interface.html", "group__mchtmr__interface" ],
    [ "MONO driver APIs", "group__mono__interface.html", "group__mono__interface" ],
    [ "OTP driver APIs", "group__otp__interface.html", "group__otp__interface" ],
    [ "PCFG driver APIs", "group__pcfg__interface.html", "group__pcfg__interface" ],
    [ "PDM driver APIs", "group__pdm__interface.html", "group__pdm__interface" ],
    [ "PDMA driver APIs", "group__pdma__interface.html", "group__pdma__interface" ],
    [ "PLIC driver APIs", "group__plic__interface.html", "group__plic__interface" ],
    [ "PLLCTL driver APIs", "group__pllctl__interface.html", "group__pllctl__interface" ],
    [ "PLLCTLV2 driver APIs", "group__pllctlv2__interface.html", "group__pllctlv2__interface" ],
    [ "PTPC driver APIs", "group__ptpc__interface.html", "group__ptpc__interface" ],
    [ "PWM driver APIs", "group__pwm__interface.html", "group__pwm__interface" ],
    [ "QEI driver APIs", "group__qei__interface.html", "group__qei__interface" ],
    [ "ROM APIs", "group__romapi__interface.html", "group__romapi__interface" ],
    [ "RTC driver APIs", "group__rtc__interface.html", "group__rtc__interface" ],
    [ "SDP driver APIs", "group__sdp__interface.html", "group__sdp__interface" ],
    [ "SDXC driver APIs", "group__sdxc__interface.html", "group__sdxc__interface" ],
    [ "SPI driver APIs", "group__spi__interface.html", "group__spi__interface" ],
    [ "SYSCTL driver APIs", "group__sysctl__interface.html", "group__sysctl__interface" ],
    [ "TRGM driver APIs", "group__trgm__interface.html", "group__trgm__interface" ],
    [ "TSNS driver APIs", "group__tsns__interface.html", "group__tsns__interface" ],
    [ "UART driver APIs", "group__uart__interface.html", "group__uart__interface" ],
    [ "USB driver APIs", "group__usb__interface.html", "group__usb__interface" ],
    [ "VAD driver APIs", "group__vad__interface.html", "group__vad__interface" ],
    [ "WDG driver APIs", "group__wdg__interface.html", "group__wdg__interface" ],
    [ "XPI NOR driver APIs", "group__xpi__nor__interface.html", "group__xpi__nor__interface" ],
    [ "XPI RAM driver APIs", "group__xpi__ram__interface.html", "group__xpi__ram__interface" ],
    [ "XPI driver APIs", "group__xpi__interface.html", "group__xpi__interface" ]
];